# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ea24466b02bf14887b4ecc09832ba91ec01db9c122683f7c98c3cc46978d8c4c1dfcb87cc77941b60e1c3e52f7d2e1a5ac15f6bac6757c608569fc28170bd07

test:
  secret_key_base: 17a062fad2e1580ffbc8b9b62cfa0b5ea22956b4fe0fc14a096f34bfe63620c717ef832e134536be1b8ccb8c00e40193325c7c3989d7272fa53fd12b86c7d18f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
